#ifndef HARDWAREPROFILE_H_INCLUDED
#define HARDWAREPROFILE_H_INCLUDED


#include <xc.h>


#define HAP_REL1_TRIS TRISAbits.TRISA12
#define HAP_REL1_LAT  LATAbits.LATA12
#define HAP_REL2_TRIS TRISAbits.TRISA0
#define HAP_REL2_LAT  LATAbits.LATA0
#define HAP_REL3_TRIS TRISAbits.TRISA1
#define HAP_REL3_LAT  LATAbits.LATA1
#define HAP_REL4_TRIS TRISBbits.TRISB0
#define HAP_REL4_LAT  LATBbits.LATB0
#define HAP_REL5_TRIS TRISBbits.TRISB1
#define HAP_REL5_LAT  LATBbits.LATB1
#define HAP_REL6_TRIS TRISBbits.TRISB2
#define HAP_REL6_LAT  LATBbits.LATB2
#define HAP_REL7_TRIS TRISBbits.TRISB3
#define HAP_REL7_LAT  LATBbits.LATB3

#define HAP_TX_TRIS  TRISCbits.TRISC7
#define HAP_RX_TRIS  TRISCbits.TRISC9
#define HAP_DIR_TRIS TRISCbits.TRISC8
#define HAP_DIR_LAT  LATCbits.LATC8

#define HAP_TEMP1_AN 7
#define HAP_TEMP2_AN 8

#define HAP_LIVELLO1_H2O_AN 12
#define HAP_LIVELLO2_H2O_AN 11

#define HAP_IN1_TRIS TRISAbits.TRISA10
#define HAP_IN1_PORT PORTAbits.RA10
#define HAP_IN2_TRIS TRISAbits.TRISA7
#define HAP_IN2_PORT PORTAbits.RA7
#define HAP_IN3_TRIS TRISBbits.TRISB14
#define HAP_IN3_PORT PORTBbits.RB14
#define HAP_IN4_TRIS TRISBbits.TRISB15
#define HAP_IN4_PORT PORTBbits.RB15

#define HAP_ASP_TRIS  TRISCbits.TRISC5
#define HAP_ASP_LAT   LATCbits.LATC5
#define HAP_SOFF_TRIS TRISCbits.TRISC4
#define HAP_SOFF_LAT  LATCbits.LATC4
#define HAP_VAP_TRIS  TRISAbits.TRISA9
#define HAP_VAP_PORT  PORTAbits.RA9

#define HAP_PWM_LIVELLI_TRIS TRISCbits.TRISC0

#define HAP_INT0_TRIS TRISBbits.TRISB7
#define HAP_INT0_PORT PORTBbits.RB7

#endif